config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homepage#show'

  resource :users, except: [:edit] do
    resource :dashboard, only: [:show, :update]
  end
  get '/users/edit/:id', to: 'users#edit', as: :edit_users
  put '/user_profile/:id', to: 'users#update', as: :update_users


  resource :admin, only: [:show]

  resources :rewards, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get "/gamble", to: 'users#gamble', as: :gamblers

  get '/user_profile/:id', to: 'users#adminshow', as: :user_profile

  get '/rewards', to: 'rewards#adminindex', as: :admin_rewards

  get '/user/:user_id/rewards/:id', to: 'users#removereward', as: :remove_reward

  get '/users/:user_id/reward/:id', to: 'users#buyreward', as: :users_buy_reward

  get '/enable_rewards/:id', to: 'rewards#enable', as: :enable_reward

  get '/disable_rewards/:id', to: 'rewards#disable', as: :disable_reward

  delete '/user_profile/:id' => 'users#destroy', as: :user_delete

  get '/all_users'     => 'users#index'

  get '/login'     => 'sessions#new'
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'

end

app/models/reward.rb
class Reward < ApplicationRecord
  has_many :user_rewards
  has_many :users, through: :user_rewards

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    if current_user
      if current_user.role == 1
        @rewards = Reward.all
        render :adminindex
      else
        @rewards = Reward.all
        @user = current_user
      end
    else
      redirect_to root_path
      flash[:notice] = 'You must be an logged in to access this page.'
    end
  end

  def show
    redirect_to rewards_path
  end

  def new
    if current_user.role == 1
      @reward = Reward.new
    else
      redirect_to root_path
      flash[:notice] = 'You must be an admin to access this page.'
    end
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      # If user saves in the db successfully:
      redirect_to rewards_path
      flash[:notice] = "Account created successfully!"
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    @reward.update(reward_params)
    if @reward.save
      # If reward saves in the db successfully:
      redirect_to rewards_path
      flash[:notice] = "Reward updated successfully!"
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't save updates. Please make sure you are using valid info and try again."
      render :edit
    end
  end

  def disable
    reward = Reward.find(params[:id])
    reward.disabled = 1
    reward.save

    redirect_to rewards_path
    flash[:notice] = "Reward #{reward.title} has been disabled."
  end

  def enable
    reward = Reward.find(params[:id])
    reward.disabled = 0
    reward.save

    redirect_to rewards_path
    flash[:notice] = "Reward #{reward.title} has been enabled."
  end

  private

  def reward_params
    params.require(:reward).permit(:title, :price)
  end
end

app/views/rewards/adminindex.html.erb
<h1>Reward Shop</h1>
<%= link_to "Create New Award", new_reward_path %>
<h2>Active Rewards</h2>
  <div class='reward-holder'>
  <% @rewards.each do |reward| %>
  <% if reward.disabled == 0 %>
    <ul class='reward-card'>
      <li><%= reward.title %></li>
      <li>Price: <%= reward.price %></li>
      <li><%= link_to "Update", edit_reward_path(reward) %></li>
      <li><%= link_to "Disable", disable_reward_path(reward) %></li>
    </ul>
  <% end %>
  <% end %>
</div>
  <h2>Disabled Rewards</h2>
  <div class='reward-holder'>
  <% @rewards.each do |reward| %>
    <% if reward.disabled == 1 %>
    <ul class='reward-card'>
      <li><%= reward.title %></li>
      <li>Price: <%= reward.price %></li>
      <li><%= link_to "Update", edit_reward_path(reward) %></li>
      <li><%= link_to "Enable", enable_reward_path(reward) %></li>
    </ul>
  <% end %>
<% end %>
</div>

app/views/rewards/edit.html.erb
<h1>Edit <%= @reward.title %> Reward Here</h1>
<div class="form">
<%= form_for @reward do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<br>
<%= f.label :price %>
<%= f.text_field :price %>
<br>
<br>
<%= f.submit %>
<% end %>
</div>

app/views/rewards/index.html.erb
<h1>Reward Shop</h1>
<div class='reward-holder'>
<% @rewards.each do |reward| %>
  <% if reward.disabled == 0 %>
    <ul class='reward-card'>
      <li><%= reward.title %></li>
      <li>Price: <%= reward.price %></li>
      <li><%= link_to "Buy", users_buy_reward_path(current_user, reward) %></li>
    </ul>
  <% end %>
<% end %>
</div>

app/views/rewards/new.html.erb
<h1>Create A New Reward Here</h1>
<div class="form">
<%= form_for @reward do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<br>
<%= f.label :price %>
<%= f.text_field :price %>
<br>
<br>
<%= f.submit %>
<% end %>
</div>