config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homepage#show'

  resource :users, except: [:edit] do
    resource :dashboard, only: [:show, :update]
  end
  get '/users/edit/:id', to: 'users#edit', as: :edit_users
  put '/user_profile/:id', to: 'users#update', as: :update_users


  resource :admin, only: [:show]

  resources :rewards, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get "/gamble", to: 'users#gamble', as: :gamblers

  get '/user_profile/:id', to: 'users#adminshow', as: :user_profile

  get '/rewards', to: 'rewards#adminindex', as: :admin_rewards

  get '/user/:user_id/rewards/:id', to: 'users#removereward', as: :remove_reward

  get '/users/:user_id/reward/:id', to: 'users#buyreward', as: :users_buy_reward

  get '/enable_rewards/:id', to: 'rewards#enable', as: :enable_reward

  get '/disable_rewards/:id', to: 'rewards#disable', as: :disable_reward

  delete '/user_profile/:id' => 'users#destroy', as: :user_delete

  get '/all_users'     => 'users#index'

  get '/login'     => 'sessions#new'
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_rewards
  has_many :rewards, through: :user_rewards
  has_secure_password
  validates :username, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if current_user
      if current_user.role == 1
        @user = User.new
      else
        redirect_to root_path
        flash[:notice] = 'You must be an admin to access this page.'
      end
    else
      redirect_to root_path
      flash[:notice] = 'You must be an admin to access this page.'
    end
  end

  def adminshow
    if current_user
      if current_user.role == 1
        @user = User.find(params[:id])
      else
        redirect_to root_path
        flash[:notice] = 'You must be an admin to access this page.'
      end
    else
      redirect_to root_path
      flash[:notice] = 'You must be an logged in to access this page.'
    end
  end

  def index
    if current_user
      if current_user.role == 1
        @users = User.all.order(id: :asc)
      else
        redirect_to root_path
        flash[:notice] = 'You must be an admin to access this page.'
      end
    else
      redirect_to root_path
      flash[:notice] = 'You must be an logged in to access this page.'
    end
  end

  def create
    @user = User.new(user_params)
    # store all usernames in lowercase to avoid duplicates
    # and case-sensitive login errors:
    @user.username.downcase!

    if @user.save
      # If user saves in the db successfully:
      flash[:notice] = "Account created successfully!"
      redirect_to root_path
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  def gamble
    @user = current_user
  end

  def edit
    # require 'pry'; binding.pry
    if current_user.role == 1
      @user = User.find(params[:id])
    else
      redirect_to root_path
      flash[:notice] = 'You must be an admin to access this page.'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      # If user saves in the db successfully:
      flash[:notice] = "Account updated successfully!"
      redirect_to update_users_path(@user)
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't save updates. Please make sure you are using valid info and try again."
      render :edit
    end
  end

  def buyreward
    # require 'pry'; binding.pry
    user = current_user
    reward = Reward.find(params[:id])
    if user.points > reward.price
      user.points -= reward.price
      user.rewards << reward
      user.redeemed_points += reward.price
      user.save
      redirect_to root_path
    else
      redirect_to rewards_path
      flash[:notice] = "Not enough points to buy! Pick a cheaper prize you bum!"
    end
  end

  def removereward
    reward = Reward.find(params[:id])
    user = User.find(params[:user_id])
    user.rewards.delete(reward)
    redirect_to user_profile_path(user)
    flash[:notice] = "#{reward.title} has been removed from rewards"
  end

  def destroy
    user = User.find(params[:id])
    user.delete

    redirect_to all_users_path
    flash[:notice] = "User #{user.name} has been deleted."
  end

  private

  def user_params
    # strong parameters -
    # whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a
    # form to the user model #=> require(:user)
    params.require(:user).permit(:name, :username, :password, :points, :redeemed_points, :password_confirmation, :role)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/adminshow.html.erb
<h1><strong><%= @user.name %></strong>: <% if @user.role == 1 %><%= "Admin" %><% else %><%= "User" %><% end %></h1>
<%= link_to "See All Users", all_users_path %>
<br>
<br>
<%= link_to "Edit User/Add Points", edit_users_path(@user) %>
<br>
<br>
<%= link_to "DELETE USER", user_delete_path(@user), method: :DELETE %>
<div class="user-show">
<ul>
  <li>Points: <%= @user.points %></li>
  <li>Redeemed Points: <%= @user.redeemed_points %></li>
  <li><h2>Rewards: </h2></li>
  <div class='user-reward-holder'>
    <ul class='user-reward-show'>
      <% @user.rewards.each do |reward| %>
      <ul class='user-reward-card'>
        <li><%= reward.title %>:</li>
        <li><%= reward.price %>pts</li>
      </ul>
      <% end %>
    </ul>
  </div>
</ul>
</div>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>
<div class='form-new'>
<%= form_for @user, url: user_profile_path(@user), html: { method: :put } do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name%>
  </div>
  <br>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <br>
  <div>
    <%= f.label :points %>
    <%= f.text_field :points %>
  </div>
  <br>
  <div>
    <%= f.label :redeemed_points %>
    <%= f.text_field :redeemed_points %>
  </div>
<br>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
<br>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <br>
  <div>
    <%= f.label :role %>
    <%= f.text_field :role  %>
  </div>
  <br>
  <div>
    <%= f.submit "Submit Changes" %>
  </div>
<% end %>
</div>

app/views/users/gamble.html.erb
<h1>Risk Some Points!</h1>
<div class="form">
<%= form_for @user, url: users_dashboard_path do |f| %>
<%= f.label :points %>
<%= f.text_field :points %>
<br>
<br>
<%= f.submit "Roll the Dice!" %>
<% end %>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>
<h4><%= link_to "Create A New User", new_users_path %></h4>
<div class='user-holder'>
<% @users.each do |user| %>
  <ul class='user-card'>
    <li><%= link_to user.name, user_profile_path(user) %></li>
    <li>Role: <% if user.role == 1 %> <%= "Admin" %> <% else %> <%= "User" %> <% end %></li>
    <li>Points: <%= user.points %></li>
    <li>Redeemed Points: <%= user.redeemed_points %></li>
    <li>Rewards: <%= user.rewards.count %></li>
    <li><%= link_to "Edit User/Add Points", edit_users_path(user) %></li>
  </ul>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Create New User</h1>
<div class="form-new">
<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <br>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
<br>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <br>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <br>
  <div>
    <%= f.label :role %>
    <%= f.text_field :role  %>
  </div>
  <br>
  <div>
    <%= f.submit "Create User" %>
  </div>
<% end %>
</div>